// Full emoji dataset with Italian keyword search index
// Every emoji in the picker has Italian keywords for search

export const EMOJI_CATEGORIES: { name: string; emojis: string[] }[] = [
    {
        name: 'Faccine', emojis: [
            '😀', '😃', '😄', '😁', '😆', '😅', '🤣', '😂', '🙂', '🙃', '😉', '😊', '😇', '🥰', '😍', '🤩',
            '😘', '😗', '😚', '😙', '🥲', '😋', '😛', '😜', '🤪', '😝', '🤑', '🤗', '🤭', '🤫', '🤔', '🫢',
            '🤐', '🤨', '😐', '😑', '😶', '🫥', '😏', '😒', '🙄', '😬', '🤥', '😌', '😔', '😪', '🤤', '😴',
            '😷', '🤒', '🤕', '🤢', '🤮', '🥵', '🥶', '🥴', '😵', '🤯', '🤠', '🥳', '🥸', '😎', '🤓', '🧐',
            '😤', '😠', '😡', '🤬', '😈', '👿', '💀', '☠️', '💩', '🤡', '👹', '👺', '👻', '👽', '👾', '🤖',
            '😺', '😸', '😹', '😻', '😼', '😽', '🙀', '😿', '😾',
        ]
    },
    {
        name: 'Persone', emojis: [
            '👶', '👧', '🧒', '👦', '👩', '🧑', '👨', '👩‍🦱', '🧑‍🦱', '👨‍🦱', '👩‍🦰', '🧑‍🦰', '👨‍🦰',
            '👱‍♀️', '👱', '👱‍♂️', '👩‍🦳', '🧑‍🦳', '👨‍🦳', '👩‍🦲', '🧑‍🦲', '👨‍🦲', '🧔‍♀️', '🧔', '🧔‍♂️',
            '👵', '🧓', '👴', '👲', '👳‍♀️', '👳', '👳‍♂️', '🧕', '👮‍♀️', '👮', '👮‍♂️', '👷‍♀️', '👷', '👷‍♂️',
            '💂‍♀️', '💂', '💂‍♂️', '🕵️‍♀️', '🕵️', '🕵️‍♂️', '👩‍⚕️', '🧑‍⚕️', '👨‍⚕️', '👩‍🌾', '🧑‍🌾', '👨‍🌾',
            '👩‍🍳', '🧑‍🍳', '👨‍🍳', '👩‍🎓', '🧑‍🎓', '👨‍🎓', '👩‍🎤', '🧑‍🎤', '👨‍🎤', '👩‍🏫', '🧑‍🏫', '👨‍🏫',
            '👩‍💻', '🧑‍💻', '👨‍💻', '👩‍🚀', '🧑‍🚀', '👨‍🚀', '🦸‍♀️', '🦸', '🦸‍♂️', '🦹‍♀️', '🦹', '🦹‍♂️',
            '🧙‍♀️', '🧙', '🧙‍♂️', '🧚‍♀️', '🧚', '🧚‍♂️', '🧛‍♀️', '🧛', '🧛‍♂️', '🧜‍♀️', '🧜', '🧜‍♂️',
            '🧝‍♀️', '🧝', '🧝‍♂️', '🧞‍♀️', '🧞', '🧞‍♂️', '🧟‍♀️', '🧟', '🧟‍♂️',
            '💆‍♀️', '💆', '💆‍♂️', '💇‍♀️', '💇', '💇‍♂️', '🚶‍♀️', '🚶', '🚶‍♂️', '🧍‍♀️', '🧍', '🧍‍♂️',
            '🧎‍♀️', '🧎', '🧎‍♂️', '🏃‍♀️', '🏃', '🏃‍♂️', '💃', '🕺', '👯‍♀️', '👯', '👯‍♂️',
            '🧖‍♀️', '🧖', '🧖‍♂️', '🧗‍♀️', '🧗', '🧗‍♂️',
        ]
    },
    {
        name: 'Gesti', emojis: [
            '👋', '🤚', '🖐️', '✋', '🖖', '🫱', '🫲', '🫳', '🫴', '👌', '🤌', '🤏', '✌️', '🤞', '🫰', '🤟',
            '🤘', '🤙', '👈', '👉', '👆', '🖕', '👇', '☝️', '🫵', '👍', '👎', '✊', '👊', '🤛', '🤜', '👏',
            '🙌', '🫶', '👐', '🤲', '🤝', '🙏', '💪', '🦾', '🦿', '🦵', '🦶', '👂', '🦻', '👃', '🧠', '🫀',
            '🫁', '🦷', '🦴', '👀', '👁️', '👅', '👄', '💋', '🫦',
        ]
    },
    {
        name: 'Cuori', emojis: [
            '❤️', '🧡', '💛', '💚', '💙', '💜', '🖤', '🤍', '🤎', '💔', '❤️‍🔥', '❤️‍🩹', '❣️', '💕', '💞', '💓',
            '💗', '💖', '💘', '💝', '💟', '♥️', '🫀', '💌', '💍', '💎',
        ]
    },
    {
        name: 'Animali', emojis: [
            '🐶', '🐱', '🐭', '🐹', '🐰', '🦊', '🐻', '🐼', '🐻‍❄️', '🐨', '🐯', '🦁', '🐮', '🐷', '🐽', '🐸',
            '🐵', '🙈', '🙉', '🙊', '🐒', '🐔', '🐧', '🐦', '🐤', '🐣', '🐥', '🦆', '🦅', '🦉', '🦇', '🐺',
            '🐗', '🐴', '🦄', '🐝', '🪱', '🐛', '🦋', '🐌', '🐞', '🐜', '🪰', '🪲', '🪳', '🦟', '🦗', '🕷️',
            '🦂', '🐢', '🐍', '🦎', '🦖', '🦕', '🐙', '🦑', '🦐', '🦞', '🦀', '🪸', '🐡', '🐠', '🐟', '🐬',
            '🐳', '🐋', '🦈', '🐊', '🐅', '🐆', '🦓', '🦍', '🦧', '🐘', '🦛', '🦏', '🐪', '🐫', '🦒', '🦘',
            '🦬', '🐃', '🐂', '🐄', '🐎', '🐖', '🐏', '🐑', '🦙', '🐐', '🦌', '🐕', '🐩', '🦮', '🐕‍🦺',
            '🐈', '🐈‍⬛', '🪶', '🐓', '🦃', '🦤', '🦚', '🦜', '🦢', '🦩', '🕊️', '🐇', '🦝', '🦨', '🦡',
            '🦫', '🦦', '🦥', '🐁', '🐀', '🐿️', '🦔',
        ]
    },
    {
        name: 'Natura', emojis: [
            '🌵', '🎄', '🌲', '🌳', '🌴', '🪵', '🌱', '🌿', '☘️', '🍀', '🎍', '🪴', '🎋', '🍃', '🍂', '🍁',
            '🪺', '🪹', '🍄', '🌾', '💐', '🌷', '🌹', '🥀', '🌺', '🌸', '🌼', '🌻', '🌞', '🌝', '🌛', '🌜',
            '🌚', '🌕', '🌖', '🌗', '🌘', '🌑', '🌒', '🌓', '🌔', '🌙', '🌎', '🌍', '🌏', '🪐', '💫', '⭐',
            '🌟', '✨', '⚡', '☄️', '💥', '🔥', '🌪️', '🌈', '☀️', '🌤️', '⛅', '🌥️', '☁️', '🌦️', '🌧️', '⛈️',
            '🌩️', '🌨️', '❄️', '☃️', '⛄', '🌬️', '💨', '💧', '💦', '🫧', '☔', '☂️', '🌊', '🏔️', '⛰️', '🌋',
        ]
    },
    {
        name: 'Cibo', emojis: [
            '🍏', '🍎', '🍐', '🍊', '🍋', '🍌', '🍉', '🍇', '🍓', '🫐', '🍈', '🍒', '🍑', '🥭', '🍍', '🥥',
            '🥝', '🍅', '🍆', '🥑', '🫛', '🥦', '🥬', '🥒', '🌶️', '🫑', '🌽', '🥕', '🧄', '🧅', '🥔', '🍠',
            '🫘', '🥐', '🍞', '🥖', '🫓', '🥨', '🧀', '🥚', '🍳', '🧈', '🥞', '🧇', '🥓', '🥩', '🍗', '🍖',
            '🦴', '🌭', '🍔', '🍟', '🍕', '🫔', '🌮', '🌯', '🫕', '🥙', '🧆', '🥚', '🍲', '🫙', '🥘', '🍝',
            '🍜', '🍛', '🍣', '🍱', '🥟', '🦪', '🍤', '🍙', '🍚', '🍘', '🍥', '🥠', '🥮', '🍢', '🍡', '🍧',
            '🍨', '🍦', '🥧', '🧁', '🍰', '🎂', '🍮', '🍭', '🍬', '🍫', '🍩', '🍪', '🌰', '🥜', '🍯',
            '🥛', '🫗', '☕', '🫖', '🍵', '🧃', '🥤', '🧋', '🍶', '🍺', '🍻', '🥂', '🍷', '🫙', '🥃', '🍸',
            '🍹', '🧉', '🍾', '🧊', '🥄', '🍴', '🍽️', '🥢', '🧂',
        ]
    },
    {
        name: 'Viaggi', emojis: [
            '🚗', '🚕', '🚙', '🚌', '🚎', '🏎️', '🚓', '🚑', '🚒', '🚐', '🛻', '🚚', '🚛', '🚜', '🏍️', '🛵',
            '🚲', '🛴', '🛺', '🚏', '🛣️', '🛤️', '🛞', '⛽', '🛞', '🚨', '🚥', '🚦', '🛑', '🚧',
            '⚓', '🛟', '⛵', '🚤', '🛥️', '🛳️', '⛴️', '🚢', '✈️', '🛩️', '🛫', '🛬', '🪂', '💺', '🚁',
            '🚟', '🚠', '🚡', '🛰️', '🚀', '🛸',
            '🚂', '🚃', '🚄', '🚅', '🚆', '🚇', '🚈', '🚉', '🚊', '🚝', '🚞',
            '🏠', '🏡', '🏘️', '🏚️', '🏗️', '🏢', '🏬', '🏣', '🏤', '🏥', '🏦', '🏨', '🏪', '🏫', '🏩',
            '💒', '🏛️', '⛪', '🕌', '🕍', '🛕', '🕋', '⛩️', '🛖', '🏰', '🏯',
            '🗼', '🗽', '⛲', '⛺', '🌁', '🌃', '🏙️', '🌄', '🌅', '🌆', '🌇', '🌉', '🎠', '🛝', '🎡', '🎢',
            '🎪', '🗾', '🏖️', '🏝️', '🏜️', '🌐',
        ]
    },
    {
        name: 'Oggetti', emojis: [
            '⌚', '📱', '📲', '💻', '⌨️', '🖥️', '🖨️', '🖱️', '🖲️', '💽', '💾', '💿', '📀',
            '🎮', '🕹️', '📷', '📸', '📹', '🎥', '📽️', '🎞️', '📞', '☎️', '📟', '📠',
            '📺', '📻', '🎙️', '🎚️', '🎛️', '⏱️', '⏲️', '⏰', '🕰️', '⌛', '⏳',
            '🔋', '🔌', '💡', '🔦', '🕯️', '🪔', '🧯', '🛢️',
            '💵', '💴', '💶', '💷', '🪙', '💰', '💳', '💎', '⚖️', '🪜', '🧰', '🪛', '🔧', '🔩', '⚙️',
            '🪤', '🧱', '⛓️', '🧲', '🔫', '💣', '🪓', '🔪', '🗡️', '⚔️', '🛡️', '🚬', '⚰️', '🪦', '⚱️',
            '🏺', '🔮', '📿', '🧿', '🪬', '💈', '⚗️', '🔭', '🔬', '🕳️', '🩹', '🩺', '🩻', '🩼', '💊', '💉',
            '🩸', '🧬', '🦠', '🧫', '🧪', '🌡️', '🧹', '🪠', '🧺', '🧻', '🚽', '🚿', '🛁', '🪥', '🪒', '🧴',
            '🪮', '🗝️', '🔑', '🚪', '🪑', '🛋️', '🛏️', '🛌', '🧸', '🪆', '🖼️', '🪞', '🪟',
            '📦', '📫', '📪', '📬', '📭', '📮', '🗳️', '✏️', '✒️', '🖋️', '🖊️', '🖌️', '🖍️',
            '📝', '💼', '📁', '📂', '📅', '📆', '🗒️', '🗓️', '📇', '📈', '📉', '📊', '📋', '📌', '📍',
            '📎', '🖇️', '📏', '📐', '✂️', '🗃️', '🗄️', '🗑️', '🔒', '🔓', '🔏', '🔐',
        ]
    },
    {
        name: 'Sport', emojis: [
            '⚽', '🏀', '🏈', '⚾', '🥎', '🎾', '🏐', '🏉', '🥏', '🎱', '🪀', '🪁',
            '🏓', '🏸', '🏒', '🏑', '🥍', '🏏', '🪃', '🥅', '⛳', '🪂', '🏹',
            '🎣', '🤿', '🥊', '🥋', '🎽', '🛹', '🛼', '🛷', '⛸️', '🥌', '🎿', '⛷️',
            '🏂', '🪂', '🏋️', '🤼', '🤸', '⛹️', '🤺', '🏇', '🧘', '🏄', '🏊', '🤽', '🚣', '🧗', '🚴', '🚵',
            '🏆', '🥇', '🥈', '🥉', '🏅', '🎖️', '🏵️', '🎗️', '🎫', '🎟️',
            '🎯', '🎳', '🎮', '🎲', '🧩', '♟️', '🎭', '🎨', '🎬', '🎤', '🎧', '🎼', '🎹', '🥁', '🪘',
            '🎷', '🎺', '🪗', '🎸', '🪕', '🎻', '🪈', '🎪',
        ]
    },
    {
        name: 'Simboli', emojis: [
            '🔴', '🟠', '🟡', '🟢', '🔵', '🟣', '⚫', '⚪', '🟤', '🔶', '🔷', '🔸', '🔹',
            '▪️', '▫️', '◼️', '◻️', '◾', '◽', '⬛', '⬜', '🟥', '🟧', '🟨', '🟩', '🟦', '🟪', '🟫',
            '💠', '🔘', '🔳', '🔲', '🏁', '🚩', '🎌', '🏴', '🏳️', '🏳️‍🌈', '🏳️‍⚧️', '🏴‍☠️',
            '⚠️', '🚸', '⛔', '🚫', '🚳', '🚭', '🚯', '🚱', '🚷', '📵', '🔞', '☣️', '☢️',
            '♻️', '✅', '❌', '❓', '❗', '‼️', '⁉️', '🆘', '🔰', '⭕', '✳️', '❇️', '🔆', '🔅',
            '♈', '♉', '♊', '♋', '♌', '♍', '♎', '♏', '♐', '♑', '♒', '♓', '⛎',
            '🆔', '⚛️', '🉐', '🈶', '🈚', '🈸', '🈺', '🈷️', '✴️', '🆚', '💮', '🉑',
            '🈴', '🈵', '🈹', '🈲', '🅰️', '🅱️', '🆎', '🆑', '🅾️', '🆘', '⛑️', '🔱', '📛',
            '🔰', '⭐', '🌟', '💫', '🎀', '🎁', '🎗️', '🎟️',
            '➕', '➖', '➗', '✖️', '💲', '💱',
            '©️', '®️', '™️', '🔚', '🔙', '🔛', '🔝', '🔜',
            '☑️', '✔️', '🔘', '🔴', '🟠', '🟡', '🟢', '🔵', '🟣',
        ]
    },
    {
        name: 'Bandiere', emojis: [
            '🇮🇹', '🇪🇺', '🇫🇷', '🇩🇪', '🇪🇸', '🇬🇧', '🇺🇸', '🇯🇵', '🇨🇳', '🇰🇷', '🇧🇷', '🇦🇷',
            '🇲🇽', '🇨🇦', '🇦🇺', '🇮🇳', '🇷🇺', '🇹🇷', '🇵🇹', '🇬🇷', '🇨🇭', '🇦🇹', '🇧🇪', '🇳🇱',
            '🇸🇪', '🇳🇴', '🇩🇰', '🇫🇮', '🇵🇱', '🇮🇪', '🇭🇷', '🇷🇴', '🇺🇦', '🇪🇬', '🇿🇦', '🇳🇬',
            '🇸🇦', '🇦🇪', '🇮🇱', '🇹🇭', '🇻🇳', '🇮🇩', '🇵🇭', '🇲🇾', '🇸🇬', '🇳🇿', '🇨🇴', '🇨🇱',
            '🇵🇪', '🇻🇪', '🇨🇺', '🇵🇷', '🇯🇲', '🇭🇹', '🇩🇴', '🇵🇦', '🇪🇨',
        ]
    },
];

// ─── Italian keyword search index (comprehensive for ALL emojis) ───
export const EMOJI_KEYWORDS: Record<string, string> = {
    // Faccine
    '😀': 'felice sorriso gioia contento', '😃': 'sorriso felice allegro', '😄': 'risata sorriso felice', '😁': 'ghigno sorriso', '😆': 'ridere risata', '😅': 'sudore nervoso', '🤣': 'risata rotolare', '😂': 'piangere ridere lacrime',
    '🙂': 'sorriso leggero', '🙃': 'sottosopra', '😉': 'occhiolino', '😊': 'arrossire sorriso', '😇': 'angelo aureola', '🥰': 'amore cuori', '😍': 'innamorato cuori occhi', '🤩': 'stelle eccitato',
    '😘': 'bacio cuore', '😗': 'bacio', '😚': 'bacio occhi chiusi', '😙': 'bacio sorriso', '🥲': 'sorriso triste lacrima', '😋': 'goloso lingua', '😛': 'lingua fuori', '😜': 'lingua occhiolino',
    '🤪': 'pazzo folle', '😝': 'lingua strizzare', '🤑': 'soldi ricco', '🤗': 'abbraccio', '🤭': 'ops risatina', '🤫': 'silenzio shhh', '🤔': 'pensare hmm', '🫢': 'sorpresa bocca',
    '🤐': 'chiuso zip bocca', '🤨': 'sopracciglio dubbio', '😐': 'neutro', '😑': 'neutro espressione', '😶': 'silenzio muto', '🫥': 'invisibile', '😏': 'ghigno furbo', '😒': 'annoiato noia',
    '🙄': 'occhi alzare annoiato', '😬': 'grimace smorfia', '🤥': 'bugiardo naso', '😌': 'sollievo pace', '😔': 'triste pensieroso', '😪': 'sonno stanco', '🤤': 'bava golosità', '😴': 'dormire sonno zzz',
    '😷': 'maschera malato', '🤒': 'febbre termometro', '🤕': 'ferito benda', '🤢': 'nausea verde', '🤮': 'vomitare', '🥵': 'caldo sudare', '🥶': 'freddo gelo', '🥴': 'ubriaco confuso',
    '😵': 'stordito', '🤯': 'mente esplodere shock', '🤠': 'cowboy cappello', '🥳': 'festa party compleanno', '🥸': 'travestimento', '😎': 'occhiali sole figo', '🤓': 'nerd occhiali', '🧐': 'monocolo esaminare',
    '😤': 'irritato sbuffare arrabbiato', '😠': 'arrabbiato', '😡': 'furioso rosso', '🤬': 'parolaccia bestemmia', '😈': 'diavolo sorriso', '👿': 'diavolo arrabbiato', '💀': 'teschio morto', '☠️': 'teschio ossa',
    '💩': 'cacca', '🤡': 'pagliaccio clown', '👹': 'orco demone', '👺': 'goblin demone', '👻': 'fantasma boo', '👽': 'alieno extraterrestre', '👾': 'mostro videogioco', '🤖': 'robot',
    '😺': 'gatto felice', '😸': 'gatto sorriso', '😹': 'gatto risata', '😻': 'gatto innamorato', '😼': 'gatto ghigno', '😽': 'gatto bacio', '🙀': 'gatto shock', '😿': 'gatto triste pianto', '😾': 'gatto arrabbiato',
    // Persone
    '👶': 'bambino neonato bebè', '👧': 'ragazza bambina', '🧒': 'bambino', '👦': 'ragazzo', '👩': 'donna', '🧑': 'persona adulto', '👨': 'uomo',
    '👵': 'nonna anziana', '🧓': 'anziano', '👴': 'nonno anziano', '👮': 'poliziotto', '👷': 'operaio casco', '💂': 'guardia soldato', '🕵️': 'detective investigatore',
    '👩‍⚕️': 'dottoressa medico', '👨‍⚕️': 'dottore medico', '👩‍🍳': 'cuoca chef', '👨‍🍳': 'cuoco chef', '👩‍🎓': 'laureata studentessa', '👨‍🎓': 'laureato studente',
    '👩‍🎤': 'cantante donna rockstar', '👨‍🎤': 'cantante uomo rockstar', '👩‍🏫': 'insegnante professoressa', '👨‍🏫': 'insegnante professore',
    '👩‍💻': 'programmatrice developer', '👨‍💻': 'programmatore developer', '👩‍🚀': 'astronauta donna', '👨‍🚀': 'astronauta uomo',
    '🦸': 'supereroe', '🦸‍♀️': 'supereroina', '🦸‍♂️': 'supereroe', '🦹': 'supercattivo', '🧙': 'mago stregone', '🧙‍♀️': 'strega maga', '🧚': 'fata', '🧛': 'vampiro',
    '🧜': 'sirena tritone', '🧝': 'elfo', '🧞': 'genio lampada', '🧟': 'zombie',
    '💃': 'ballerina danza', '🕺': 'ballerino danza', '🏃': 'correre corsa', '🏃‍♀️': 'correre donna', '🏃‍♂️': 'correre uomo',
    '🚶': 'camminare', '🧍': 'in piedi', '🧎': 'inginocchiato', '🧗': 'arrampicata scalare',
    // Gesti
    '👋': 'ciao saluto mano', '🤚': 'mano alzata stop', '🖐️': 'mano aperta cinque', '✋': 'mano stop alto', '🖖': 'vulcano saluto spock',
    '👌': 'ok perfetto', '🤌': 'italiano mano gesto che vuoi', '🤏': 'piccolo pizzico', '✌️': 'vittoria pace', '🤞': 'dita incrociate fortuna',
    '🤘': 'rock corna metal', '🤙': 'chiamami telefono', '👈': 'sinistra punto', '👉': 'destra punto', '👆': 'su punto', '👇': 'giù punto',
    '👍': 'ok bene pollice su', '👎': 'male pollice giù', '✊': 'pugno forza', '👊': 'pugno colpo', '👏': 'applauso bravo',
    '🙌': 'mani alzate celebrare', '🫶': 'cuore mani amore', '🤝': 'stretta mano accordo', '🙏': 'pregare grazie namaste', '💪': 'muscolo forza braccio',
    '🦿': 'gamba protesi', '🦵': 'gamba', '🦶': 'piede', '👂': 'orecchio ascoltare', '🦻': 'orecchio apparecchio', '👃': 'naso annusare',
    '🧠': 'cervello mente intelligenza', '🫀': 'cuore organo anatomico', '🫁': 'polmoni respirare', '🦷': 'dente', '🦴': 'osso',
    '👀': 'occhi guardare', '👁️': 'occhio vedere', '👅': 'lingua gusto', '👄': 'bocca labbra', '💋': 'bacio rossetto', '🫦': 'labbro mordere',
    // Cuori
    '❤️': 'cuore rosso amore', '🧡': 'cuore arancione', '💛': 'cuore giallo', '💚': 'cuore verde', '💙': 'cuore blu', '💜': 'cuore viola porpora',
    '🖤': 'cuore nero', '🤍': 'cuore bianco', '🤎': 'cuore marrone', '💔': 'cuore spezzato rotto', '❤️‍🔥': 'cuore fuoco passione',
    '❤️‍🩹': 'cuore fascia guarigione', '❣️': 'cuore esclamativo', '💕': 'due cuori', '💞': 'cuori rotanti', '💓': 'cuore battente pulsante',
    '💗': 'cuore crescente', '💖': 'cuore scintillante brillante', '💘': 'cuore freccia cupido', '💝': 'cuore regalo', '💟': 'cuore decorativo',
    '♥️': 'cuore carte', '💌': 'lettera amore', '💍': 'anello matrimonio fidanzamento', '💎': 'diamante gioiello',
    // Animali
    '🐶': 'cane cucciolo', '🐱': 'gatto micio', '🐭': 'topo topolino', '🐹': 'criceto', '🐰': 'coniglio', '🦊': 'volpe',
    '🐻': 'orso', '🐼': 'panda', '🐻‍❄️': 'orso polare bianco', '🐨': 'koala', '🐯': 'tigre', '🦁': 'leone re',
    '🐮': 'mucca', '🐷': 'maiale porco', '🐽': 'naso maiale', '🐸': 'rana', '🐵': 'scimmia faccia', '🙈': 'scimmia non vedo',
    '🙉': 'scimmia non sento', '🙊': 'scimmia non parlo', '🐒': 'scimmia', '🐔': 'gallina pollo', '🐧': 'pinguino',
    '🐦': 'uccello', '🐤': 'pulcino', '🐣': 'pulcino uovo', '🐥': 'pulcino piccolo', '🦆': 'anatra papera',
    '🦅': 'aquila', '🦉': 'gufo civetta', '🦇': 'pipistrello', '🐺': 'lupo', '🐗': 'cinghiale',
    '🐴': 'cavallo', '🦄': 'unicorno magico', '🐝': 'ape miele', '🪱': 'verme', '🐛': 'bruco', '🦋': 'farfalla',
    '🐌': 'lumaca lenta', '🐞': 'coccinella fortuna', '🐜': 'formica', '🪰': 'mosca', '🪲': 'scarabeo', '🪳': 'scarafaggio',
    '🦟': 'zanzara', '🦗': 'grillo', '🕷️': 'ragno', '🦂': 'scorpione', '🐢': 'tartaruga lenta',
    '🐍': 'serpente', '🦎': 'lucertola', '🦖': 'dinosauro rex', '🦕': 'dinosauro brontosauro', '🐙': 'polpo',
    '🦑': 'calamaro', '🦐': 'gambero', '🦞': 'aragosta', '🦀': 'granchio', '🪸': 'corallo',
    '🐡': 'pesce palla', '🐠': 'pesce tropicale', '🐟': 'pesce', '🐬': 'delfino', '🐳': 'balena spruzza',
    '🐋': 'balena', '🦈': 'squalo', '🐊': 'coccodrillo', '🐅': 'tigre', '🐆': 'leopardo ghepardo',
    '🦓': 'zebra', '🦍': 'gorilla', '🦧': 'orango', '🐘': 'elefante', '🦛': 'ippopotamo',
    '🦏': 'rinoceronte', '🐪': 'cammello dromedario', '🐫': 'cammello due gobbe', '🦒': 'giraffa', '🦘': 'canguro',
    '🦬': 'bisonte', '🐃': 'bufalo', '🐂': 'bue', '🐄': 'mucca', '🐎': 'cavallo corsa',
    '🐖': 'maiale', '🐏': 'ariete', '🐑': 'pecora', '🦙': 'lama alpaca', '🐐': 'capra',
    '🦌': 'cervo renna', '🐕': 'cane', '🐩': 'barboncino', '🐈': 'gatto', '🐈‍⬛': 'gatto nero',
    '🪶': 'piuma', '🐓': 'gallo', '🦃': 'tacchino', '🦤': 'dodo estinto', '🦚': 'pavone',
    '🦜': 'pappagallo', '🦢': 'cigno', '🦩': 'fenicottero', '🕊️': 'colomba pace',
    '🐇': 'coniglio', '🦝': 'procione', '🦨': 'puzzola', '🦡': 'tasso', '🦫': 'castoro',
    '🦦': 'lontra', '🦥': 'bradipo pigro', '🐁': 'topo', '🐀': 'ratto', '🐿️': 'scoiattolo', '🦔': 'riccio',
    // Natura
    '🌵': 'cactus deserto', '🎄': 'albero natale', '🌲': 'abete pino', '🌳': 'albero', '🌴': 'palma tropicale', '🪵': 'legno tronco',
    '🌱': 'germoglio piantina', '🌿': 'erba foglia', '☘️': 'trifoglio', '🍀': 'quadrifoglio fortuna', '🪴': 'pianta vaso',
    '🍃': 'foglia vento', '🍂': 'foglia autunno', '🍁': 'foglia acero', '🍄': 'fungo', '🌾': 'grano riso spiga',
    '💐': 'bouquet fiori mazzo', '🌷': 'tulipano', '🌹': 'rosa fiore', '🥀': 'fiore appassito', '🌺': 'ibisco fiore',
    '🌸': 'ciliegio fiore sakura', '🌼': 'margherita fiore', '🌻': 'girasole',
    '🌞': 'sole faccia', '🌝': 'luna piena faccia', '🌛': 'luna faccia', '🌜': 'luna faccia', '🌚': 'luna nuova faccia',
    '🌙': 'luna mezzaluna', '🌎': 'terra americhe', '🌍': 'terra europa africa', '🌏': 'terra asia',
    '🪐': 'pianeta saturno anelli', '💫': 'stella cadente girare', '⭐': 'stella', '🌟': 'stella brillante', '✨': 'scintille brillare',
    '⚡': 'fulmine elettricità', '☄️': 'cometa', '💥': 'esplosione boom', '🔥': 'fuoco fiamma caldo',
    '🌪️': 'tornado', '🌈': 'arcobaleno', '☀️': 'sole', '⛅': 'nuvola sole', '☁️': 'nuvola',
    '🌧️': 'pioggia', '⛈️': 'temporale', '🌩️': 'fulmine', '🌨️': 'neve', '❄️': 'fiocco neve',
    '☃️': 'pupazzo neve', '⛄': 'pupazzo neve', '🌬️': 'vento soffiare', '💨': 'vento velocità',
    '💧': 'goccia acqua', '💦': 'gocce sudore', '🫧': 'bolle sapone', '☔': 'pioggia ombrello', '☂️': 'ombrello', '🌊': 'onda mare',
    '🏔️': 'montagna neve', '⛰️': 'montagna', '🌋': 'vulcano eruzione',
    // Cibo
    '🍏': 'mela verde', '🍎': 'mela rossa', '🍐': 'pera', '🍊': 'arancia mandarino', '🍋': 'limone', '🍌': 'banana', '🍉': 'anguria cocomero', '🍇': 'uva',
    '🍓': 'fragola', '🫐': 'mirtillo', '🍈': 'melone', '🍒': 'ciliegia', '🍑': 'pesca', '🥭': 'mango', '🍍': 'ananas', '🥥': 'cocco',
    '🥝': 'kiwi', '🍅': 'pomodoro', '🍆': 'melanzana', '🥑': 'avocado', '🫛': 'pisello', '🥦': 'broccoli', '🥬': 'insalata lattuga', '🥒': 'cetriolo',
    '🌶️': 'peperoncino piccante', '🫑': 'peperone', '🌽': 'mais pannocchia', '🥕': 'carota', '🧄': 'aglio', '🧅': 'cipolla', '🥔': 'patata', '🍠': 'patata dolce',
    '🫘': 'fagioli', '🥐': 'cornetto croissant', '🍞': 'pane', '🥖': 'baguette francese', '🫓': 'piadina', '🥨': 'pretzel', '🧀': 'formaggio', '🥚': 'uovo',
    '🍳': 'uovo fritto padella', '🧈': 'burro', '🥞': 'pancake', '🧇': 'waffle', '🥓': 'bacon pancetta', '🥩': 'bistecca carne',
    '🍗': 'coscia pollo', '🍖': 'costoletta carne', '🌭': 'hot dog', '🍔': 'hamburger panino', '🍟': 'patatine fritte', '🍕': 'pizza',
    '🫔': 'tamale', '🌮': 'taco', '🌯': 'burrito', '🫕': 'fonduta', '🥙': 'pita kebab', '🧆': 'falafel',
    '🍲': 'stufato zuppa pentola', '🥘': 'paella tegame', '🍝': 'spaghetti pasta', '🍜': 'ramen noodle brodo',
    '🍛': 'curry riso', '🍣': 'sushi', '🍱': 'bento giapponese', '🥟': 'raviolo', '🦪': 'ostrica',
    '🍤': 'gambero fritto tempura', '🍙': 'onigiri riso', '🍚': 'riso ciotola', '🍘': 'cracker riso', '🍥': 'narutomaki',
    '🥠': 'biscotto fortuna', '🥮': 'torta luna', '🍢': 'oden', '🍡': 'dango', '🍧': 'granita ghiaccio',
    '🍨': 'gelato coppetta', '🍦': 'gelato cono', '🥧': 'torta crostata', '🧁': 'cupcake', '🍰': 'torta fetta',
    '🎂': 'torta compleanno candeline', '🍮': 'budino crème caramel', '🍭': 'lecca lecca', '🍬': 'caramella', '🍫': 'cioccolato',
    '🍩': 'ciambella donut', '🍪': 'biscotto cookie', '🌰': 'castagna', '🥜': 'arachidi noccioline', '🍯': 'miele vasetto',
    '🥛': 'latte bicchiere', '🫗': 'versare', '☕': 'caffè tazza', '🫖': 'teiera', '🍵': 'tè matcha', '🧃': 'succo brick',
    '🥤': 'bibita cannuccia', '🧋': 'bubble tea boba', '🍶': 'sake', '🍺': 'birra boccale', '🍻': 'birra brindisi cin cin',
    '🥂': 'champagne brindisi spumante', '🍷': 'vino rosso', '🥃': 'whisky', '🍸': 'cocktail martini', '🍹': 'cocktail tropicale',
    '🧉': 'mate', '🍾': 'champagne bottiglia festa', '🧊': 'ghiaccio cubo', '🥄': 'cucchiaio', '🍴': 'forchetta coltello',
    '🍽️': 'piatto posate', '🥢': 'bacchette', '🧂': 'sale',
    // Viaggi
    '🚗': 'macchina auto', '🚕': 'taxi', '🚙': 'suv auto', '🚌': 'autobus bus', '🚎': 'filobus', '🏎️': 'formula corsa',
    '🚓': 'polizia auto', '🚑': 'ambulanza', '🚒': 'pompieri vigili fuoco', '🚐': 'furgone minibus', '🛻': 'camion pickup',
    '🚚': 'camion', '🚛': 'tir camion', '🚜': 'trattore', '🏍️': 'moto motocicletta', '🛵': 'scooter vespa',
    '🚲': 'bicicletta bici', '🛴': 'monopattino', '🛺': 'risciò tuk tuk', '🚏': 'fermata bus',
    '🛣️': 'autostrada', '🛤️': 'ferrovia binari', '⛽': 'benzina carburante', '🚨': 'sirena polizia emergenza',
    '🚥': 'semaforo', '🚦': 'semaforo', '🛑': 'stop alt', '🚧': 'lavori cantiere',
    '⚓': 'ancora nave', '⛵': 'barca vela', '🚤': 'motoscafo', '🛥️': 'yacht barca', '🛳️': 'nave crociera', '⛴️': 'traghetto',
    '🚢': 'nave', '✈️': 'aereo volo', '🛩️': 'aereo piccolo', '🛫': 'decollo partenza', '🛬': 'atterraggio arrivo',
    '🪂': 'paracadute', '💺': 'sedile aereo', '🚁': 'elicottero', '🛰️': 'satellite', '🚀': 'razzo spazio', '🛸': 'ufo alieno disco',
    '🚂': 'treno locomotiva vapore', '🚃': 'vagone treno', '🚄': 'treno alta velocità', '🚅': 'treno veloce shinkansen',
    '🚆': 'treno', '🚇': 'metro metropolitana', '🚈': 'metro leggera', '🚉': 'stazione treno', '🚊': 'tram', '🚝': 'monorotaia', '🚞': 'treno montagna',
    '🏠': 'casa', '🏡': 'casa giardino', '🏘️': 'case quartiere', '🏚️': 'casa abbandonata', '🏗️': 'costruzione cantiere gru',
    '🏢': 'ufficio edificio', '🏬': 'centro commerciale', '🏣': 'ufficio postale', '🏥': 'ospedale', '🏦': 'banca',
    '🏨': 'hotel albergo', '🏪': 'negozio', '🏫': 'scuola', '🏩': 'love hotel', '💒': 'matrimonio chiesa',
    '🏛️': 'museo parlamento colonne', '⛪': 'chiesa', '🕌': 'moschea', '🕍': 'sinagoga', '🛕': 'tempio induista', '🕋': 'kaaba mecca',
    '⛩️': 'torii giapponese', '🛖': 'capanna', '🏰': 'castello europeo', '🏯': 'castello giapponese',
    '🗼': 'torre eiffel', '🗽': 'statua libertà new york', '⛲': 'fontana', '⛺': 'tenda campeggio',
    '🌃': 'notte città', '🏙️': 'skyline città', '🌄': 'alba montagna', '🌅': 'tramonto', '🌆': 'crepuscolo sera',
    '🌉': 'ponte notte', '🎠': 'giostra cavalli', '🛝': 'scivolo', '🎡': 'ruota panoramica', '🎢': 'montagne russe', '🎪': 'circo tendone',
    '🏖️': 'spiaggia ombrellone', '🏝️': 'isola deserta', '🏜️': 'deserto', '🌐': 'globo mondo internet',
    // Oggetti
    '⌚': 'orologio polso', '📱': 'telefono cellulare smartphone', '📲': 'telefono freccia', '💻': 'computer portatile laptop',
    '⌨️': 'tastiera', '🖥️': 'computer desktop monitor', '🖨️': 'stampante', '🖱️': 'mouse', '🖲️': 'trackball',
    '💽': 'minidisc', '💾': 'floppy disk', '💿': 'cd disco', '📀': 'dvd',
    '🎮': 'controller gioco videogioco', '🕹️': 'joystick gioco arcade', '📷': 'fotocamera macchina fotografica', '📸': 'fotocamera flash',
    '📹': 'videocamera', '🎥': 'cinema film cinepresa', '📽️': 'proiettore', '🎞️': 'pellicola film',
    '📞': 'telefono fisso cornetta', '☎️': 'telefono retro', '📟': 'cercapersone', '📠': 'fax',
    '📺': 'televisione tv', '📻': 'radio', '🎙️': 'microfono studio podcast', '🎚️': 'mixer audio',
    '🎛️': 'manopole', '⏱️': 'cronometro', '⏲️': 'timer', '⏰': 'sveglia', '🕰️': 'orologio pendolo',
    '⌛': 'clessidra', '⏳': 'clessidra scorre', '🔋': 'batteria', '🔌': 'spina presa elettrica', '💡': 'lampadina idea',
    '🔦': 'torcia flashlight', '🕯️': 'candela', '🪔': 'lampada olio', '🧯': 'estintore', '🛢️': 'barile petrolio',
    '💵': 'dollaro banconota', '💴': 'yen', '💶': 'euro soldi', '💷': 'sterlina', '🪙': 'moneta',
    '💰': 'sacco soldi', '💳': 'carta credito', '💎': 'diamante gioiello', '⚖️': 'bilancia giustizia',
    '🪜': 'scala', '🧰': 'cassetta attrezzi', '🪛': 'cacciavite', '🔧': 'chiave inglese', '🔩': 'dado bullone', '⚙️': 'ingranaggio',
    '🔫': 'pistola acqua', '💣': 'bomba', '🪓': 'ascia', '🔪': 'coltello cucina', '🗡️': 'spada', '⚔️': 'spade incrociate', '🛡️': 'scudo difesa',
    '🚬': 'sigaretta fumare', '⚰️': 'bara', '🪦': 'lapide tomba', '⚱️': 'urna', '🏺': 'anfora vaso',
    '🔮': 'sfera cristallo magia', '📿': 'rosario', '🧿': 'malocchio nazar', '💈': 'barbiere',
    '⚗️': 'alambicco chimica', '🔭': 'telescopio', '🔬': 'microscopio', '🕳️': 'buco', '🩹': 'cerotto',
    '🩺': 'stetoscopio medico', '💊': 'pillola medicina', '💉': 'siringa vaccino iniezione', '🩸': 'goccia sangue',
    '🧬': 'dna genetica', '🦠': 'virus batterio microbo', '🧫': 'petri', '🧪': 'provetta', '🌡️': 'termometro temperatura',
    '🧹': 'scopa', '🪠': 'sturalavandini', '🧺': 'cesto bucato', '🧻': 'carta igienica', '🚽': 'gabinetto wc',
    '🚿': 'doccia', '🛁': 'vasca bagno', '🪥': 'spazzolino denti', '🪒': 'rasoio', '🧴': 'lozione crema',
    '🗝️': 'chiave antica', '🔑': 'chiave', '🚪': 'porta', '🪑': 'sedia', '🛋️': 'divano', '🛏️': 'letto',
    '🧸': 'orsetto peluche teddy', '🪆': 'matrioska russa', '🖼️': 'quadro cornice', '🪞': 'specchio', '🪟': 'finestra',
    '📦': 'pacco scatola', '📫': 'cassetta posta', '📮': 'cassetta postale',
    '✏️': 'matita', '✒️': 'penna inchiostro', '🖋️': 'penna stilografica', '🖊️': 'penna biro', '🖌️': 'pennello', '🖍️': 'pastello',
    '📝': 'nota memo scrivere', '💼': 'valigetta lavoro', '📁': 'cartella', '📂': 'cartella aperta', '📅': 'calendario',
    '📈': 'grafico crescita', '📉': 'grafico calo', '📊': 'grafico barre', '📋': 'clipboard', '📌': 'puntina', '📍': 'segnaposto',
    '📎': 'graffetta', '📏': 'righello', '📐': 'squadra', '✂️': 'forbici', '🗑️': 'cestino spazzatura', '🔒': 'lucchetto chiuso', '🔓': 'lucchetto aperto',
    // Sport
    '⚽': 'calcio pallone', '🏀': 'basket pallacanestro', '🏈': 'football americano', '⚾': 'baseball', '🥎': 'softball', '🎾': 'tennis palla racchetta',
    '🏐': 'pallavolo', '🏉': 'rugby', '🥏': 'frisbee disco', '🎱': 'biliardo', '🪀': 'yoyo', '🪁': 'aquilone',
    '🏓': 'ping pong tennis tavolo', '🏸': 'badminton volano', '🏒': 'hockey ghiaccio', '🏑': 'hockey prato',
    '🥍': 'lacrosse', '🏏': 'cricket', '🪃': 'boomerang', '🥅': 'porta rete', '⛳': 'golf buca', '🏹': 'arco freccia',
    '🎣': 'pesca canna', '🤿': 'immersione snorkeling', '🥊': 'boxe pugilato', '🥋': 'karate judo arti marziali',
    '🎽': 'maglia corsa', '🛹': 'skateboard', '🛼': 'pattini rotelle', '🛷': 'slitta', '⛸️': 'pattini ghiaccio',
    '🥌': 'curling', '🎿': 'sci', '⛷️': 'sciatore', '🏂': 'snowboard', '🏋️': 'pesi palestra sollevamento',
    '🤼': 'lotta wrestling', '🤸': 'ginnastica acrobazia', '⛹️': 'basket pallone', '🤺': 'scherma', '🏇': 'equitazione cavallo',
    '🧘': 'yoga meditazione', '🏄': 'surf onda', '🏊': 'nuoto piscina', '🤽': 'pallanuoto', '🚣': 'canoa remo',
    '🧗': 'arrampicata scalare', '🚴': 'ciclismo bici', '🚵': 'mountain bike',
    '🏆': 'trofeo coppa vittoria', '🥇': 'medaglia oro primo', '🥈': 'medaglia argento secondo', '🥉': 'medaglia bronzo terzo',
    '🏅': 'medaglia sport', '🎖️': 'medaglia militare', '🏵️': 'rosetta premio', '🎗️': 'nastro consapevolezza', '🎫': 'biglietto', '🎟️': 'biglietto evento',
    '🎯': 'bersaglio freccette centro', '🎳': 'bowling birilli', '🎮': 'videogioco controller', '🎲': 'dado gioco dadi',
    '🧩': 'puzzle tessera', '♟️': 'scacchi pedone', '🎭': 'teatro maschere commedia tragedia', '🎨': 'arte tavolozza pittura colori',
    '🎬': 'ciak cinema', '🎤': 'microfono karaoke cantare', '🎧': 'cuffie musica', '🎼': 'spartito note musica',
    '🎹': 'pianoforte tastiera', '🥁': 'tamburo batteria', '🪘': 'djembe tamburo', '🎷': 'sassofono sax',
    '🎺': 'tromba', '🪗': 'fisarmonica', '🎸': 'chitarra rock', '🪕': 'banjo', '🎻': 'violino', '🪈': 'flauto', '🎪': 'circo tendone',
    // Simboli
    '🔴': 'cerchio rosso', '🟠': 'cerchio arancione', '🟡': 'cerchio giallo', '🟢': 'cerchio verde', '🔵': 'cerchio blu', '🟣': 'cerchio viola',
    '⚫': 'cerchio nero', '⚪': 'cerchio bianco', '🟤': 'cerchio marrone',
    '🏁': 'bandiera scacchi traguardo', '🚩': 'bandiera rossa', '🏳️‍🌈': 'arcobaleno pride lgbtq', '🏴‍☠️': 'bandiera pirata',
    '⚠️': 'attenzione pericolo', '⛔': 'divieto vietato', '🚫': 'proibito', '♻️': 'riciclo ecologia',
    '✅': 'spunta verde ok fatto', '❌': 'croce no sbagliato', '❓': 'domanda', '❗': 'esclamativo importante',
    '🆘': 'sos aiuto emergenza', '⭕': 'cerchio', '✳️': 'asterisco', '❇️': 'scintilla',
    '➕': 'più addizione', '➖': 'meno sottrazione', '➗': 'diviso divisione', '✖️': 'per moltiplicazione',
    '💲': 'dollaro prezzo', '©️': 'copyright', '®️': 'registrato', '™️': 'trademark marchio',
    // Bandiere
    '🇮🇹': 'italia italiano', '🇪🇺': 'europa unione europea', '🇫🇷': 'francia francese', '🇩🇪': 'germania tedesco',
    '🇪🇸': 'spagna spagnolo', '🇬🇧': 'inghilterra regno unito inglese', '🇺🇸': 'stati uniti america americano',
    '🇯🇵': 'giappone giapponese', '🇨🇳': 'cina cinese', '🇰🇷': 'corea sud coreano', '🇧🇷': 'brasile brasiliano',
    '🇦🇷': 'argentina argentino', '🇲🇽': 'messico messicano', '🇨🇦': 'canada canadese', '🇦🇺': 'australia australiano',
    '🇮🇳': 'india indiano', '🇷🇺': 'russia russo', '🇹🇷': 'turchia turco', '🇵🇹': 'portogallo portoghese',
    '🇬🇷': 'grecia greco', '🇨🇭': 'svizzera svizzero', '🇦🇹': 'austria austriaco', '🇧🇪': 'belgio belga',
    '🇳🇱': 'olanda paesi bassi olandese', '🇸🇪': 'svezia svedese', '🇳🇴': 'norvegia norvegese',
    '🇩🇰': 'danimarca danese', '🇫🇮': 'finlandia finlandese', '🇵🇱': 'polonia polacco',
    '🇮🇪': 'irlanda irlandese', '🇭🇷': 'croazia croato', '🇷🇴': 'romania romeno', '🇺🇦': 'ucraina ucraino',
    '🇪🇬': 'egitto egiziano', '🇿🇦': 'sudafrica', '🇳🇬': 'nigeria nigeriano',
    '🇸🇦': 'arabia saudita', '🇦🇪': 'emirati arabi dubai', '🇮🇱': 'israele israeliano',
    '🇹🇭': 'thailandia tailandese', '🇻🇳': 'vietnam vietnamita', '🇮🇩': 'indonesia indonesiano',
    '🇵🇭': 'filippine filippino', '🇲🇾': 'malesia', '🇸🇬': 'singapore', '🇳🇿': 'nuova zelanda',
    '🇨🇴': 'colombia colombiano', '🇨🇱': 'cile cileno', '🇵🇪': 'perù peruviano', '🇻🇪': 'venezuela venezuelano',
    '🇨🇺': 'cuba cubano', '🇵🇷': 'porto rico', '🇯🇲': 'giamaica', '🇭🇹': 'haiti', '🇩🇴': 'dominicana',
    '🇵🇦': 'panama', '🇪🇨': 'ecuador',
};
