-- 20260222_ai_telemetry_logs.sql
-- Creates the telemetry table to track AI events and metrics according to MVP spec

CREATE TYPE ai_event_type AS ENUM (
    'session_recommended',
    'session_started',
    'session_completed',
    'insight_viewed',
    'question_explained',
    'bando_queried'
);

CREATE TABLE IF NOT EXISTS public.ai_telemetry_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    event_type ai_event_type NOT NULL,
    session_data JSONB DEFAULT '{}'::jsonb, -- Store filters, configs, and session parameters generated by AI
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Index for querying analytics faster (e.g. by user and event type)
CREATE INDEX IF NOT EXISTS ai_telemetry_logs_user_id_idx ON public.ai_telemetry_logs(user_id);
CREATE INDEX IF NOT EXISTS ai_telemetry_logs_event_type_idx ON public.ai_telemetry_logs(event_type);
CREATE INDEX IF NOT EXISTS ai_telemetry_logs_created_at_idx ON public.ai_telemetry_logs(created_at);

-- RLS
ALTER TABLE public.ai_telemetry_logs ENABLE ROW LEVEL SECURITY;

-- Users can insert their own telemetry
CREATE POLICY "Users can insert their own ai telemetry" 
ON public.ai_telemetry_logs 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- Users can view their own telemetry (might be needed for streak/stats on frontend)
CREATE POLICY "Users can view their own ai telemetry" 
ON public.ai_telemetry_logs 
FOR SELECT 
USING (auth.uid() = user_id);

-- Admins can view all telemetry
CREATE POLICY "Admins can view all ai telemetry" 
ON public.ai_telemetry_logs 
FOR SELECT 
USING (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);
